---
- name: install prometheus
  community.kubernetes.helm:
    name: kube-prometheus
    chart_ref: https://charts.bitnami.com/bitnami/kube-prometheus-5.0.4.tgz
    release_namespace: monitoring
    create_namespace: true
    values:
      prometheus:
        persistence:
          enabled: true
          storageClass: "longhorn-replica1-retain"
        ingress:
          enabled: true
          hostname: "prometheus.{{ domain }}"
      node-exporter:
        tolerations:
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "CriticalAddonsOnly"
            operator: "Exists"
            effect: "NoSchedule"
      alertmanager:
        ingress:
          enabled: true
          hostname: "alertmanager.{{ domain }}"
    wait: true
    binary_path: "{{ _kube_master['kubernetes']['info']['helm_path'] }}"
    kubeconfig: "{{ _kube_master['kubernetes']['info']['kubeconfig'] }}"
