---
- name: install python3-openshift
  yum:
    name: python3-openshift
    state: installed
  become: true
  become_user: root

- include_tasks: apps_longhorn.yml
  vars:
    _kube_master: "{{ hostvars|dict2items|get_kubernetes_master(app.value.kubernetes.configs.cluster_name) }}"
  when: _kube_master['kubernetes']['configs']['features']['longhorn']['enabled']|default(false)

- include_tasks: apps_prometheus.yml
  vars:
    _kube_master: "{{ hostvars|dict2items|get_kubernetes_master(app.value.kubernetes.configs.cluster_name) }}"
  when: _kube_master['kubernetes']['configs']['features']['prometheus']['enabled']|default(false)

- include_tasks: apps_metallb.yml
  vars:
    _kube_master: "{{ hostvars|dict2items|get_kubernetes_master(app.value.kubernetes.configs.cluster_name) }}"
  when: _kube_master['kubernetes']['configs']['features']['metallb']['enabled']|default(false)
