---
- block:
    - name: setup rke2 repository 1
      yum_repository:
        name: rancher-rke2-common-latest
        description: Rancher RKE2 Common Latest
        baseurl: "https://rpm.rancher.io/rke2/latest/common/centos/{{ ansible_distribution_major_version }}/noarch"
        gpgkey: https://rpm.rancher.io/public.key
        gpgcheck: true

    - name: setup rke2 repository 2
      yum_repository:
        name: rancher-rke2-1-18-latest
        description: Rancher RKE2 1.18 Latest
        baseurl: "https://rpm.rancher.io/rke2/latest/1.18/centos/{{ ansible_distribution_major_version }}/x86_64"
        gpgkey: https://rpm.rancher.io/public.key
        gpgcheck: true

    - name: install rke2-server
      yum:
        name: rke2-server
        state: installed
      when: app.value.kubernetes.configs.type == "master"

    - name: install rke2-agent
      yum:
        name: rke2-agent
        state: installed
      when: app.value.kubernetes.configs.type == "worker"

    - name: create rke2 config dir
      file:
        path: /etc/rancher/rke2/
        state: directory
        mode: 0755

    - block:
        - name: install iscsi-initiator-utils if needed
          yum:
            name: iscsi-initiator-utils
            state: present

        - name: start iscsi
          service:
            name: iscsid
            state: started
            enabled: true
      vars:
        _kube_master: "{{ hostvars|dict2items|get_kubernetes_master(app.value.kubernetes.configs.cluster_name) }}"
      when: _kube_master['kubernetes']['configs']['features']['longhorn']['enabled']|default(false)
  become: true
  become_user: root
