---
- name: debug
  debug:
    msg: "Jeste kubernetese"
- name: set default flags
  set_fact:
    _kubernetes_cluster_exists: false
- block:
    - include_tasks: consul_discovery.yml

    - block:
        - include_tasks: "install.yml"
        # if node token exists, the node is part of a cluster
        - name: look for node-token
          stat:
            path: /var/lib/rancher/rke2/server/node-token
          register: _node_token_stat

        - block:
            - name: start existing cluster
              service:
                name: rke2-server
                state: started

            - include_tasks: wait_for_node.yml

            - name: set flag about existing cluster
              set_fact:
                _kubernetes_cluster_exists: true
              run_once: true

          when: _node_token_stat.stat.exists

        - include_tasks: "configure.yml"  # bootstrap
          when: not _kubernetes_cluster_exists and app.value.kubernetes.configs.type == "master"
          run_once: true

        - include_tasks: "configure.yml"  # configure rest of nodes

      when: app.value.kubernetes.configs.type in  ["master", "worker"]

    - include_tasks: "apps.yml"
      when: app.value.kubernetes.configs.type == "apps"
      run_once: true

  become: true
  become_user: root

- name: flush handlers
  meta: flush_handlers

- name: dirty wait for cluster to start
  pause:
    seconds: 180
  when: app.value.kubernetes.configs.type == "worker"
